### ISSUE TITLE
Can c++ impls of torch::nn::Module be bound back to python?

### ISSUE THREAD

**Issue by kevindarby** [prabhuomkar/pytorch-cpp#109]
Hi, 

I just had a general quesiton as to whether one of these Modules, such as 

```class VAEImpl : public torch::nn::Module {```

could be somehow bound back to python and used (in training, inference etc) back in python land?

I am currently under the impression that this is impossible and that only new ops can be created in c++ and used in python

https://pytorch.org/tutorials/advanced/cpp_extension.html

Thanks,

Kevin

**Comment by mfl28** [comment]
Hi! 
Going from C++ to Python in this way currently seems to be possible only for torchscript models (see e.g. [here](https://github.com/pytorch/pytorch/issues/35464)). For more infos you may want to ask in the [official PyTorch forums](https://discuss.pytorch.org/).
