### ISSUE TITLE
 binary '<<': no operator found which takes a right-hand operand of type 'const Value' 

### ISSUE THREAD

**Issue by amarnathreddy0201** [prabhuomkar/pytorch-cpp#110]
C:\pytorch-cpp-master\libtorch\include\torch\csrc\api\include\torch/serialize.h(43,3): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'const Value' (or there is no acceptab
le conversion) [C:\pytorch-cpp-master\build\pytorch-cpp.vcxproj].

Initially I followed basics from Pytorch it's showing C:/Program Files/Nvidia Corporation/NvToolsExt/include missing.

I followed you're method from master branch It showing  binary '<<': no operator found which takes a right-hand operand of type 'const Value'  in pytorch-cpp-master\libtorch\include\torch\csrc\api\include\torch/serialize.h(43,3).

**Comment by amarnathreddy0201** [comment]
I am using image data set dog and cat
I followed below link.
1) https://krshrimali.github.io/posts/2019/07/classifying-dogs-vs-cats-using-pytorch-c-api-part-1/

**Comment by mfl28** [comment]
If I understand correctly, you are following a different tutorial at the link you posted. If this is the case, you might want to ask the person that created that one.
If however you have a problem with one of the tutorials in this repo (pytorch-cpp), please give more details about the exact tutorial where your problem occurs and which version of libtorch you are using.

**Comment by mfl28** [comment]
Closing this for now.
