### ISSUE TITLE
How to initialize tensor from gpu memory

### ISSUE THREAD

**Issue by wangzhenlin123** [prabhuomkar/pytorch-cpp#111]
`#include <torch/torch.h>
#include <iostream>

int main() {
    float* gpu_data;
    cudaMalloc(&gpu_data, 10 * sizeof(float));

    float* host_data = new float[10];
    for (int i = 0; i < 10; ++i) {
        host_data[i] = static_cast<float>(i);
    }

   cudaMemcpy(gpu_data, host_data, 10 * sizeof(float), cudaMemcpyHostToDevice);

    float* cpu_data = new float[10];
    cudaMemcpy(cpu_data, gpu_data, 10 * sizeof(float), cudaMemcpyDeviceToHost);

    torch::TensorOptions options(torch::kFloat32);

    torch::Tensor tensor = torch::from_blob(cpu_data, {10}, options);

  
    std::cout << "Tensor values: " << tensor << std::endl;

    cudaFree(gpu_data);
    delete[] host_data;
    delete[] cpu_data;

    return 0;
}`

i needl to initialize tensor from gpu memory，but the this way is wrong，how to do it？

**Comment by mfl28** [comment]
This is libtorch-specific question (and not directly related to any of the tutorials) - the [Pytorch discussion forums](https://discuss.pytorch.org/) would be a better fit for this question!
