### ISSUE TITLE
Saving and loading models

### ISSUE THREAD

**Issue by AmadouTidjani** [prabhuomkar/pytorch-cpp#112]
Hello,

After training a convolutional neural network, how to save properly the model ?

I have tried with `torch::save(model, serialized_out_path)` and `torch::load(model, serialized_input_path)`, but it didn't work.

Thanks in advance!

**Comment by mfl28** [comment]
This seems to be possible only for torchscript models (i.e. saving from C++ and then loading from Python) (similar question answered in https://github.com/prabhuomkar/pytorch-cpp/issues/109).
