### ISSUE TITLE
Set CUDA as default device in torch C++

### ISSUE THREAD

**Issue by AmadouTidjani** [prabhuomkar/pytorch-cpp#113]
Hello,

Please, How can I set CUDA as default device in torch C++? I use libtorch 1.13.1 cu117

Thanks in advance!

**Comment by mfl28** [comment]
You can define your device somewhere like this:
```c++
torch::Device device(torch::cuda::is_available() ? torch::kCUDA : torch::kCPU);
```

**Comment by AmadouTidjani** [comment]
Thanks
