### ISSUE TITLE
omp_set_num_threads should only be called in serial regions

### ISSUE THREAD

**Issue by jfulem** [prabhuomkar/pytorch-cpp#115]
Please, don't you know why I'm getting this when I call some torch model forward() method and the input is a 3D Tensor, where the first dimension is a batch size? Thank you.

**Comment by mfl28** [comment]
This seems to be a libtorch-specific issue and not directly related to any of the tutorials - the [Pytorch discussion forums](https://discuss.pytorch.org/) would be a better fit for this question!
