### ISSUE TITLE
Loading Keypoint RCNN on C++

### ISSUE THREAD

**Issue by roboticswithamir** [prabhuomkar/pytorch-cpp#116]
Hi, I'm trying to load  torchvision.models.detection.keypointrcnn_resnet50_fpn on C++ but I had no success. I'm actually loading and training it on Python first, I'm not sure if it's the right way or not. I just leave the codes below for more info:

Python:

```
import torch

import torchvision

model = torchvision.models.detection.keypointrcnn_resnet50_fpn()

# An example input you would normally provide to your model's forward() method.

example = torch.rand(1, 3, 224, 224)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.

traced_script_module = torch.jit.script(model, example)

traced_script_module.save("rcnn_model.pt")
```

C++:

```
#include <iostream>
#include <torch/torch.h>
#include <torch/script.h>

int main()
{

	torch::jit::script::Module model;
	
    try 
    {
    model = torch::jit::load("/home/bluesky/Documents/Codes/AI/Keypoint_RCNN/rcnn_model.pt");
    } 
    
    catch (const c10::Error& e) 
    {
        std::cerr << "Error loading the model: " << e.msg() << std::endl;
    }
}
```

CMake:

```
cmake_minimum_required(VERSION 3.2)

project(torchtest)

set(CMAKE_PREFIX_PATH /home/bluesky/Downloads/libtorch-cxx11-abi-shared-with-deps-1.8.0+cu112/libtorch)
find_package(Torch REQUIRED)
 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
 
add_executable(${PROJECT_NAME} main.cpp)
 
target_link_libraries(${PROJECT_NAME} "${TORCH_LIBRARIES}")
 
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 14)
```

**Comment by mfl28** [comment]
This is libtorch-specific question and not directly related to any of the tutorials - the [Pytorch discussion forums](https://discuss.pytorch.org/) would be a better fit for this question!

**Comment by roboticswithamir** [comment]
I actually opened a topic on Pytorch forums and also their github repo long time ago. You could check my comments over Pytorch community [here](https://discuss.pytorch.org/t/keypoint-rcnn-on-c/181757) and Vision github repo [here](https://github.com/pytorch/vision/issues/7697). torch.jit doesn't apparently work for torchvision detection models. The only solutions seems to be reimplementing a full RCNN model on C++ from scratch. It could be a possible add-on for alter releases over this repo.
