### ISSUE TITLE
Expression: vector subscript out of range

### ISSUE THREAD

**Issue by alance123** [prabhuomkar/pytorch-cpp#31]
In the tutorial of deep residual net. In the cifar.cpp, for the function--std::pair<torch::Tensor, torch::Tensor> read_data(const std::string& root, bool train),  it works well in linux, but when in win10, i got the following error.

![error](https://user-images.githubusercontent.com/17922415/74830573-68dba100-534e-11ea-835a-7bc79c638e2a.jpg)

**Comment by mfl28** [comment]
Thanks for reporting the error! 
I could reproduce it in Windows 10 using Visual Studio 2017 in Debug config and using libtorch Debug version (it was working with Release mode).
Fix is coming in a PR.

**Comment by prabhuomkar** [comment]
@alance123 can you check? The fix is on master now.

**Comment by alance123** [comment]
@prabhuomkar, I checked, the issue is fixed, thank you very much.
