### ISSUE TITLE
Why does Libtorch use more memory than Pytorch does in Python？ Such as:ESRGAN

### ISSUE THREAD

**Issue by qingfengmingyue** [prabhuomkar/pytorch-cpp#56]
Why does Libtorch use more memory than Pytorch does in Python？ Such as:ESRGAN

**Comment by prabhuomkar** [comment]
We don't have an implementation of ESRGAN in our repository.
Considering this being a general question related to memory usage, can you give us metrics how you calculated the memory usage for both?

**Comment by qingfengmingyue** [comment]
Directly predict in two ways, on the 1080TI libtorch can only predict 200*200, and the other can predict 800*800

**Comment by qingfengmingyue** [comment]
> Considering this being a general question related to memory usage, can you give us metrics and code on how you calculated the memory usage for both?

Directly predict in two ways, on the 1080TI libtorch can only predict 200*200, and the other can predict 800*800

**Comment by qingfengmingyue** [comment]
> Considering this being a general question related to memory usage, can you give us metrics and code on how you calculated the memory usage for both?

Directly predict in two ways, on the 2080TI libtorch can only predict 200X200, and the other can predict 800X800

**Comment by prabhuomkar** [comment]
@qingfengmingyue waiting for some more information and want to know if its related to any example from this repository?

**Comment by prabhuomkar** [comment]
closing as stale and not provided enough input.
