### ISSUE TITLE
Hope for support for YOLOv3 object detection model.

### ISSUE THREAD

**Issue by ouening** [prabhuomkar/pytorch-cpp#61]
Hi, your work is very awesome! And I hope you can add support for yolov3 model if you have time because yolov3 is very popular in object detection.

**Comment by prabhuomkar** [comment]
@ouening do you have a reference Python implementation for YOLOv3?

**Comment by ouening** [comment]
Yes, but the API is old, not compatible with the latest libtorch.

**Comment by ouening** [comment]
I have solved the version compatiable problem. See https://github.com/walktree/libtorch-yolov3/issues/52#issue-686915754
