### ISSUE TITLE
[feature] ImageNet Dataset Example

### ISSUE THREAD

**Issue by prabhuomkar** [prabhuomkar/pytorch-cpp#73]
Required via https://github.com/pytorch/pytorch/issues/34862#issuecomment-695136418

**Comment by prabhuomkar** [comment]
Will be working on weekend, should be available by Monday

**Comment by soumyadipghosh** [comment]
@prabhuomkar Is there any update? Thanks.

**Comment by soumyadipghosh** [comment]
@prabhuomkar Following up?

**Comment by prabhuomkar** [comment]
Hey sorry @soumyadipghosh due to some technical circumstances, couldn't really work on this. 

Let me cc: @mfl28 
Can you take this up Markus over weekend?
I'll try this weekend though. Apologies for that.

**Comment by soumyadipghosh** [comment]
@prabhuomkar Okay, let me know when there is any draft code.

**Comment by mfl28** [comment]
[Here](https://gist.github.com/mfl28/0bf2637a156bb8073fbcd2feffe1b22c) I have implemented a simple ImageFolder dataset. It requires C++17  for `<filesystem>` and was tested using libtorch 1.9.0 and the [imagenette](https://github.com/fastai/imagenette) dataset (a subset of ImageNet).

**Comment by prabhuomkar** [comment]
@mfl28 is there a chance you can create a PR for the ImageNet dataset and add as a part of `basics` or `popular` ?

**Comment by mfl28** [comment]
@prabhuomkar This would require setting the C++ version to c++17 just for this new tutorial as all others currently use c++14. I can update the c++ version of all tutorials to c++17 but that would probably mean losing support for some (very old) compiler versions. However, after a quick check at least all compilers used in our CI seem to fully support c++17.

**Comment by prabhuomkar** [comment]
Then yes, let's go for it. I can take a look at the PR.

**Comment by prabhuomkar** [comment]
@soumyadipghosh closing this as an example is added
