### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by cvchanghao** [prabhuomkar/pytorch-cpp#74]
I use `torch.jit.trace()` and save my own CNN_model. The return of my network is a tuple contains 3 tensors.
When I use C++ as front, I use `auto output = module.forward(inputs);` to get my result. But how can I get the 3 tensors individually? and do some C++ operations?

Thank you!

**Comment by mfl28** [comment]
`script::module`'s `forward` method returns an `IValue` type that has many methods to convert to other types, see [here](https://pytorch.org/cppdocs/api/structc10_1_1_i_value.html?highlight=ivalue). You might want to try `toTensorList()`, `toTensorVector()` or `toTuple()`.

**Comment by mfl28** [comment]
Closing this for now, hope I could help you with your problem :)
