### ISSUE TITLE
[feature] Switch to Github Actions CI.

### ISSUE THREAD

**Issue by mfl28** [prabhuomkar/pytorch-cpp#77]
**Is your feature request related to a problem? Please describe.**
* I'd suggest we switch from Travis CI to Github Actions CI as Travis seems to no longer allow unlimited free builds for open-source projects (see [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)).

**Describe the solution you'd like**
* Remove the Travis CI setup and add equivalent Github Actions CI setup.

**Comment by prabhuomkar** [comment]
Will take a look into and create a PR!
