### ISSUE TITLE
Wasserstein Metric criterion

### ISSUE THREAD

**Issue by wesboyt** [prabhuomkar/pytorch-cpp#80]
I need to predict discrete density functions that have ordinal information.

I would like an earth movers distance implementation for my work.

I'm currently using KL divergence

**Comment by mfl28** [comment]
The purpose of this repo is to provide tutorials to get people started with PyTorch's C++ API. If you have an idea for a new tutorial please open an issue (and - if you already implemented your idea - a PR) with a detailed description. For your specific issue, you might get help by asking in the Pytorch discussion forum or the official Pytorch Github issues.
