### ISSUE TITLE
Have dataloader for ImageNet

### ISSUE THREAD

**Issue by faranaziz** [prabhuomkar/pytorch-cpp#81]
**Is your feature request related to a problem? Please describe.**
I want have load ImageNet, not MNIST. 

**Describe the solution you'd like**
To have a dataloader for ImageNet that works with training one of the models. 

Thnaks.

**Comment by mfl28** [comment]
[Here](https://gist.github.com/mfl28/0bf2637a156bb8073fbcd2feffe1b22c) I have implemented a simple ImageFolder dataset. It requires C++17  for `<filesystem>` and was tested using libtorch 1.9.0 and the [imagenette](https://github.com/fastai/imagenette) dataset (a subset of ImageNet).
