### ISSUE TITLE
How to use ModuleList？

### ISSUE THREAD

**Issue by iDestro** [prabhuomkar/pytorch-cpp#82]
I found that in this project, there is no code using ModuleList. I recently encountered some problems in using ModuleList.If you can give some examples, thank you very much.

**Comment by mfl28** [comment]
Hi @iDestro !
Can you give more details about the problems you encountered using `ModuleList`?

**Comment by mfl28** [comment]
You might want to take a look at the implementations/documentation/tests at:
* https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/modules/container/modulelist.h
* https://github.com/ShahriarSS/pytorch/blob/master/test/cpp/api/modulelist.cpp
