### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by baik33** [prabhuomkar/pytorch-cpp#96]
Hello there,

I'm having this problem:
[ 21%] Building CXX object tutorials/intermediate/convolutional_neural_network/CMakeFiles/convolutional-neural-network.dir/src/main.cpp.o
/root/ml/pytorch-cpp/tutorials/intermediate/convolutional_neural_network/src/main.cpp: In function 'int main()':
/root/ml/pytorch-cpp/tutorials/intermediate/convolutional_neural_network/src/main.cpp:106:12: error: 'InferenceMode' is not a member of 'torch'
     torch::InferenceMode no_grad;
            ^~~~~~~~~~~~~

What could be the cause?

Thank you!

**Comment by prabhuomkar** [comment]
what is the version of libtorch you’re using?

**Comment by baik33** [comment]
I think I've figured out what the problem is.  Thank you Omkar!
